version: '3'

networks:
  apibookstore:
    driver: bridge

services:
  cache:
    container_name: cache
    image: redis:latest
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - ${CACHE_PORT}:${CACHE_PORT}
    networks:
      - apibookstore
    command: redis-server --bind 0.0.0.0 --port $CACHE_PORT --requirepass $CACHE_PASS

  data:
    container_name: data
    image: mysql:latest
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ${DB_DATA}=/var/lib/mysql
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - apibookstore
